from typing import Any


class WMI_Class:
    def __init__(self, dict: dict):
        for key, value in dict.items():
            setattr(self, key, value)

class Win32_PerfRawData_PerfOS_System (WMI_Class):
  AlignmentFixupsPerSec: int
  Caption: str
  ContextSwitchesPerSec: int
  Description: str
  ExceptionDispatchesPerSec: int
  FileControlBytesPerSec: int
  FileControlOperationsPerSec: int
  FileDataOperationsPerSec: int
  FileReadBytesPerSec: int
  FileReadOperationsPerSec: int
  FileWriteBytesPerSec: int
  FileWriteOperationsPerSec: int
  FloatingEmulationsPerSec: int
  Frequency_Object: int
  Frequency_PerfTime: int
  Frequency_Sys100NS: int
  Name: str
  PercentRegistryQuotaInUse: int
  Processes: int
  ProcessorQueueLength: int
  SystemCallsPerSec: int
  SystemUpTime: int
  Threads: int
  Timestamp_Object: int
  Timestamp_PerfTime: int
  Timestamp_Sys100NS: int

class Win32_PerfRawData_PerfOS_Memory (WMI_Class):
    AvailableBytes: Any
    AvailableKBytes: Any
    AvailableMBytes: Any
    CacheBytes: Any
    CacheBytesPeak: Any
    CacheFaultsPersec: Any
    Caption: Any
    CommitLimit: Any
    CommittedBytes: Any
    DemandZeroFaultsPersec: Any
    Description: Any
    FreeAndZeroPageListBytes: Any
    FreeSystemPageTableEntries: Any
    Frequency_Object: Any
    Frequency_PerfTime: Any
    Frequency_Sys100NS: Any
    LongTermAverageStandbyCacheLifetimes: Any
    ModifiedPageListBytes: Any
    Name: Any
    PageFaultsPersec: Any
    PageReadsPersec: Any
    PagesInputPersec: Any
    PagesOutputPersec: Any
    PagesPersec: Any
    PageWritesPersec: Any
    PercentCommittedBytesInUse: Any
    PercentCommittedBytesInUse_Base: Any
    PoolNonpagedAllocs: Any
    PoolNonpagedBytes: Any
    PoolPagedAllocs: Any
    PoolPagedBytes: Any
    PoolPagedResidentBytes: Any
    StandbyCacheCoreBytes: Any
    StandbyCacheNormalPriorityBytes: Any
    StandbyCacheReserveBytes: Any
    SystemCacheResidentBytes: Any
    SystemCodeResidentBytes: Any
    SystemCodeTotalBytes: Any
    SystemDriverResidentBytes: Any
    SystemDriverTotalBytes: Any
    Timestamp_Object: Any
    Timestamp_PerfTime: Any
    Timestamp_Sys100NS: Any
    TransitionFaultsPersec: Any
    TransitionPagesRePurposedPersec: Any
    WriteCopiesPersec: Any

class Win32_PerfRawData_PerfDisk_LogicalDisk(WMI_Class):
    AvgDiskBytesPerRead: Any
    AvgDiskBytesPerRead_Base: Any
    AvgDiskBytesPerTransfer: Any
    AvgDiskBytesPerTransfer_Base: Any
    AvgDiskBytesPerWrite: Any
    AvgDiskBytesPerWrite_Base: Any
    AvgDiskQueueLength: Any
    AvgDiskReadQueueLength: Any
    AvgDisksecPerRead: Any
    AvgDisksecPerRead_Base: Any
    AvgDisksecPerTransfer: Any
    AvgDisksecPerTransfer_Base: Any
    AvgDisksecPerWrite: Any
    AvgDisksecPerWrite_Base: Any
    AvgDiskWriteQueueLength: Any
    Caption: Any
    CurrentDiskQueueLength: Any
    Description: Any
    DiskBytesPersec: Any
    DiskReadBytesPersec: Any
    DiskReadsPersec: Any
    DiskTransfersPersec: Any
    DiskWriteBytesPersec: Any
    DiskWritesPersec: Any
    FreeMegabytes: Any
    Frequency_Object: Any
    Frequency_PerfTime: Any
    Frequency_Sys100NS: Any
    Name: Any
    PercentDiskReadTime: Any
    PercentDiskReadTime_Base: Any
    PercentDiskTime: Any
    PercentDiskTime_Base: Any
    PercentDiskWriteTime: Any
    PercentDiskWriteTime_Base: Any
    PercentFreeSpace: Any
    PercentFreeSpace_Base: Any
    PercentIdleTime: Any
    PercentIdleTime_Base: Any
    SplitIOPerSec: Any
    Timestamp_Object: Any
    Timestamp_PerfTime: Any
    Timestamp_Sys100NS: Any

class Win32_PerfRawData_Tcpip_NetworkInterface (WMI_Class):
    BytesReceivedPersec: Any
    BytesSentPersec: Any
    BytesTotalPersec: Any
    Caption: Any
    CurrentBandwidth: Any
    Description: Any
    Frequency_Object: Any
    Frequency_PerfTime: Any
    Frequency_Sys100NS: Any
    Name: Any
    OffloadedConnections: Any
    OutputQueueLength: Any
    PacketsOutboundDiscarded: Any
    PacketsOutboundErrors: Any
    PacketsPersec: Any
    PacketsReceivedDiscarded: Any
    PacketsReceivedErrors: Any
    PacketsReceivedNonUnicastPersec: Any
    PacketsReceivedPersec: Any
    PacketsReceivedUnicastPersec: Any
    PacketsReceivedUnknown: Any
    PacketsSentNonUnicastPersec: Any
    PacketsSentPersec: Any
    PacketsSentUnicastPersec: Any
    TCPActiveRSCConnections: Any
    TCPRSCAveragePacketSize: Any
    TCPRSCCoalescedPacketsPersec: Any
    TCPRSCExceptionsPersec: Any
    Timestamp_Object: Any
    Timestamp_PerfTime: Any
    Timestamp_Sys100NS: Any

class Win32_PerfRawData_PerfOS_Processor (WMI_Class):
    C1TransitionsPersec: Any
    C2TransitionsPersec: Any
    C3TransitionsPersec: Any
    Caption: Any
    Description: Any
    DPCRate: Any
    DPCsQueuedPersec: Any
    Frequency_Object: Any
    Frequency_PerfTime: Any
    Frequency_Sys100NS: Any
    InterruptsPersec: Any
    Name: Any
    PercentC1Time: Any
    PercentC2Time: Any
    PercentC3Time: Any
    PercentDPCTime: Any
    PercentIdleTime: Any
    PercentInterruptTime: Any
    PercentPrivilegedTime: Any
    PercentProcessorTime: Any
    PercentUserTime: Any
    Timestamp_Object: Any
    Timestamp_PerfTime: Any
    Timestamp_Sys100NS: Any

class Win32_PerfRawData_Counters_SMBServer (WMI_Class):
    Caption: Any
    Description: Any
    Frequency_Object: Any
    Frequency_PerfTime: Any
    Frequency_Sys100NS: Any
    Name: Any
    ReadBytesPersec: Any
    ReadRequestsPersec: Any
    ReceiveBytesPersec: Any
    SendBytesPersec: Any
    Timestamp_Object: Any
    Timestamp_PerfTime: Any
    Timestamp_Sys100NS: Any
    WriteBytesPersec: Any
    WriteRequestsPersec: Any

class Win32_OperatingSystem (WMI_Class):
    BootDevice: Any
    BuildNumber: Any
    BuildType: Any
    Caption: Any
    CodeSet: Any
    CountryCode: Any
    CreationClassName: Any
    CSCreationClassName: Any
    CSDVersion: Any
    CSName: Any
    CurrentTimeZone: Any
    DataExecutionPrevention_32BitApplications: Any
    DataExecutionPrevention_Available: Any
    DataExecutionPrevention_Drivers: Any
    DataExecutionPrevention_SupportPolicy: Any
    Debug: Any
    Description: Any
    Distributed: Any
    EncryptionLevel: Any
    ForegroundApplicationBoost: Any
    FreePhysicalMemory: Any
    FreeSpaceInPagingFiles: Any
    FreeVirtualMemory: Any
    InstallDate: Any
    LargeSystemCache: Any
    LastBootUpTime: Any
    LocalDateTime: Any
    Locale: Any
    Manufacturer: Any
    MaxNumberOfProcesses: Any
    MaxProcessMemorySize: Any
    MUILanguages: Any
    Name: Any
    NumberOfLicensedUsers: Any
    NumberOfProcesses: Any
    NumberOfUsers: Any
    OperatingSystemSKU: Any
    Organization: Any
    OSArchitecture: Any
    OSLanguage: Any
    OSProductSuite: Any
    OSType: Any
    OtherTypeDescription: Any
    PAEEnabled: Any
    PlusProductID: Any
    PlusVersionNumber: Any
    PortableOperatingSystem: Any
    Primary: Any
    ProductType: Any
    RegisteredUser: Any
    SerialNumber: Any
    ServicePackMajorVersion: Any
    ServicePackMinorVersion: Any
    SizeStoredInPagingFiles: Any
    Status: Any
    SuiteMask: Any
    SystemDevice: Any
    SystemDirectory: Any
    SystemDrive: Any
    TotalSwapSpaceSize: Any
    TotalVirtualMemorySize: Any
    TotalVisibleMemorySize: Any
    Version: Any
    WindowsDirectory: Any